/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart' | '/restaurant/$id' | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/restaurant/$id' | '/track/$id'
  id: '__root__' | '/' | '/cart' | '/restaurant/$id' | '/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  TrackIdRoute: typeof TrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  TrackIdRoute: TrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
